### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by jiminjung2334** [oceanstar777/HUFS_OSS#2]
전: ### 한국외대 오픈소스소프트웨어과목 실습입니다.
후: ### 한국외국어대학교 오픈소스소프트웨어과목 실습입니다.

학교에 대한 풀네임을 넣는게 낫다고 생각되어 한국외대 -> 한국외국어 대학교로 commit해놓았습니다. 참고해주세요.

**Comment by oceanstar777** [comment]
확인했습니다!
